<?php
// necesitamos la trayectoria de la URL para formar las rutas:
global $URL_PATH;

?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="robots" content="noindex,nofollow">

    <title>
        <?php \dawfony\Ti::startBlock("title"); ?>
        SocialLove
        <?php \dawfony\Ti::endBlock(); ?>
    </title>

    <?php /* jquery cdn */ ?>
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <?php /* Bootstrap. Las rutas deben ser absolutas, porque estamos haciendo rewrite */ ?>
    <link rel="stylesheet" href="<?= $URL_PATH ?>/vendor/twbs/bootstrap/dist/css/bootstrap.min.css">
    <script src="<?= $URL_PATH ?>/vendor/twbs/bootstrap/dist/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="<?= $URL_PATH ?>/node_modules/bootstrap-social/bootstrap-social.css">
    <?php /* Font awesome CDN */ ?>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/font-awesome.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/solid.min.css">
    <link rel="stylesheet" href="<?= $URL_PATH ?>/node_modules/font-awesome/css/font-awesome.min.css">
    <?php /* Animate.css CDN */ ?>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
    <?php /*Para añadir lineas al head desde las plantillas derivadas*/ ?>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <?php \dawfony\Ti::startBlock("head"); ?>
    <?php \dawfony\Ti::endBlock(); ?>

    <style>
        body {
            background-color: #1c2228;
        }

        footer {
            color: white;
        }

        h1 {
            color: white;
        }

        .acepted {
            color: white;
            background-color: purple;
        }

        p {
            color: white;
            text-align: center;
        }

        .imagen-fondo {
            background-image: url("<?= $URL_PATH ?>/assets/fotosInterfaces/redsocial.png");
            background-repeat: no-repeat;
            background-size: 100% 100%;
            height: 450px;
        }

        .inscripcion {
            float: right;
        }

        .flickr {
            background: #f40083;
            color: white;
        }

        .g {
            background-color: rgba(0, 0, 0, 0.2);
            margin: 45px;
            padding: 25px;
        }
        .prueba{
            background-color: #1c2228 ;
        }
        
    </style>

</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col">
                <header class="header-content" id="header-content">
                    <h1 class="">
                        <img class="img-fluid" src="<?= $URL_PATH ?>/assets/fotosInterfaces/logo.png" data-srcpng="" alt="socialLove.localhost">
                    </h1>
            </div>
            <br>
            <center>
                <div class="col">
                    <form class="form-loggin excluded-bind-register" action="#" method="post">
                        <div class="form-row">
                            <div class="col ">
                                <input class="input-square" type="text" id="mail" name="username" placeholder="correo electrónico" value="">
                            </div>
                            <div class="col ">
                                <input class="input-square" type="password" id="password" name="password" value="" placeholder="contraseña">
                            </div>
                            <div class="col ">
                                <button type="submit" class="btn acepted">OK</button>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-cell form-cell-large">
                                <a class="password-lost-link white open-modal" href="#">¿Has olvidado tu contraseña?</a>
                            </div>
                        </div>
                    </form>
                </div>
            </center>
        </div>
    </div>

    </header>
    <hr>
    <br>


    <div class="imagen-fondo">
        <div class="container-fluid ">
            <div class="inscripcion g">
                <br>
                <h1>Inscripción gratuita</h1>
                <p class="">en menos de un minuto</p>
                <div class="">
                    <div class="form-row">
                        <form action="#" method="post">

                    </div>
                    <form action="#" class="">
                        <div class="text-center">
                            <a href="" class="btn btn-block mb-4 flickr" data-toggle="modal" data-target="#modalContactForm">
                                ME INSCRIBO</a>
                        </div>
                        <button class="btn btn-default btn-social btn-facebook">
                            <i class="fa fa-facebook"></i> Conexión vía Facebook </button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- ********************** Modal ******************************************* -->
    <div class="modal fade" id="modalContactForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog"  role="document">
            <div class="modal-content">
                <div class="modal-header text-center" >
                    <h4 class="modal-title w-100 font-weight-bold">Regístrate</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body mx-3">

                    <div class="md-form mb-5">
                        <i class="fas fa-venus-mars"></i>
                        <label class="">
                            <select name="sex" id="register-sex" class="required">
                                <option value="">yo soy...</option>
                                <option value="1">una mujer</option>
                                <option value="0">un hombre</option>
                            </select>
                        </label>
                    </div>
                    <div class="md-form mb-5">
                        <i class="fas fa-user prefix grey-text"></i>
                        <label data-error="wrong" data-success="right" for="form34">Nombre</label>
                        <input type="text" id="form34" class="form-control validate">
                        
                    </div>
                    <div class="md-form mb-5">
                        <i class="fas fa-envelope prefix grey-text"></i>
                        <label data-error="wrong" data-success="right" for="form29">E-mail</label>
                        <input type="email" id="form29" class="form-control validate">
                        
                    </div>
                    <div class="md-form mb-5">
                        <i class="fas fa-lock"></i>
                                <label>Contraseña</label>
                                <div class="input-group">
                                    <input ID="txtPassword" type="Password" Class="form-control">
                                    <div class="input-group-append">
                                        <button id="show_password" class="btn btn-dark" type="button" onclick="mostrarPassword()"> <span class="fa fa-eye-slash icon"></span> </button>
                                    </div>
                                </div>
                        </label>
                    </div>
                    <div class="md-form mb-5">

                        <i class="fas fa-calendar"></i>
                        <label>Fecha Nacimiento</label><br>
                        <select id="day" name="day" class="">
                            <option value="JJ">DD</option>
                            <option value="01">01</option>
                            <option value="02">02</option>
                            <option value="03">03</option>
                            <option value="04">04</option>
                            <option value="05">05</option>
                            <option value="06">06</option>
                            <option value="07">07</option>
                            <option value="08">08</option>
                            <option value="09">09</option>
                            <option value="10">10</option>
                            <option value="11">11</option>
                            <option value="12">12</option>
                            <option value="13">13</option>
                            <option value="14">14</option>
                            <option value="15">15</option>
                            <option value="16">16</option>
                            <option value="17">17</option>
                            <option value="18">18</option>
                            <option value="19">19</option>
                            <option value="20">20</option>
                            <option value="21">21</option>
                            <option value="22">22</option>
                            <option value="23">23</option>
                            <option value="24">24</option>
                            <option value="25">25</option>
                            <option value="26">26</option>
                            <option value="27">27</option>
                            <option value="28">28</option>
                            <option value="29">29</option>
                            <option value="30">30</option>
                            <option value="31">31</option>
                        </select>
                        </label>
                        <label class="">
                            <select id="month" name="month" class="">
                                <option value="MM">MM</option>
                                <option value="1">01</option>
                                <option value="2">02</option>
                                <option value="3">03</option>
                                <option value="4">04</option>
                                <option value="5">05</option>
                                <option value="6">06</option>
                                <option value="7">07</option>
                                <option value="8">08</option>
                                <option value="9">09</option>
                                <option value="10">10</option>
                                <option value="11">11</option>
                                <option value="12">12</option>
                            </select>
                        </label>
                        <label class="">
                            <select id="year" name="year" class="">
                                <option value="AA">AA</option>
                                <option value="2002">2002</option>
                                <option value="2001">2001</option>
                                <option value="2000">2000</option>
                                <option value="1999">1999</option>
                                <option value="1998">1998</option>
                                <option value="1997">1997</option>
                                <option value="1996">1996</option>
                                <option value="1995">1995</option>
                                <option value="1994">1994</option>
                                <option value="1993">1993</option>
                                <option value="1992">1992</option>
                                <option value="1991">1991</option>
                                <option value="1990">1990</option>
                                <option value="1989">1989</option>
                                <option value="1988">1988</option>
                                <option value="1987">1987</option>
                                <option value="1986">1986</option>
                                <option value="1985">1985</option>
                                <option value="1984">1984</option>
                                <option value="1983">1983</option>
                                <option value="1982">1982</option>
                                <option value="1981">1981</option>
                                <option value="1980">1980</option>
                                <option value="1979">1979</option>
                                <option value="1978">1978</option>
                                <option value="1977">1977</option>
                                <option value="1976">1976</option>
                                <option value="1975">1975</option>
                                <option value="1974">1974</option>
                                <option value="1973">1973</option>
                                <option value="1972">1972</option>
                                <option value="1971">1971</option>
                                <option value="1970">1970</option>
                                <option value="1969">1969</option>
                                <option value="1968">1968</option>
                                <option value="1967">1967</option>
                                <option value="1966">1966</option>
                                <option value="1965">1965</option>
                                <option value="1964">1964</option>
                                <option value="1963">1963</option>
                                <option value="1962">1962</option>
                                <option value="1961">1961</option>
                                <option value="1960">1960</option>
                                <option value="1959">1959</option>
                                <option value="1958">1958</option>
                                <option value="1957">1957</option>
                                <option value="1956">1956</option>
                                <option value="1955">1955</option>
                                <option value="1954">1954</option>
                                <option value="1953">1953</option>
                                <option value="1952">1952</option>
                                <option value="1951">1951</option>
                                <option value="1950">1950</option>
                                <option value="1949">1949</option>
                                <option value="1948">1948</option>
                                <option value="1947">1947</option>
                                <option value="1946">1946</option>
                                <option value="1945">1945</option>
                                <option value="1944">1944</option>
                                <option value="1943">1943</option>
                                <option value="1942">1942</option>
                                <option value="1941">1941</option>
                                <option value="1940">1940</option>
                            </select>
                        </label>
                    </div>
                </div>
                <div class="modal-footer d-flex justify-content-center">
                    <button class="btn btn-unique">Enviar <i class="fas fa-paper-plane ml-1"></i></button>
                </div>
            </div>
        </div>
    </div>

    <?php \dawfony\Ti::startBlock("content"); ?>


    <?php \dawfony\Ti::endBlock(); ?>
    <footer class="rounded p-4 mt-2 text-center  myfont">
        © <?= date("Y") ?> 2ºDAW
    </footer>
</body>

<script type="text/javascript">
    function mostrarPassword() {
        var cambio = document.getElementById("txtPassword");
        if (cambio.type == "password") {
            cambio.type = "text";
            $('.icon').removeClass('fa fa-eye-slash').addClass('fa fa-eye');
        } else {
            cambio.type = "password";
            $('.icon').removeClass('fa fa-eye').addClass('fa fa-eye-slash');
        }
    }

    $(document).ready(function() {
        //CheckBox mostrar contraseña
        $('#ShowPassword').click(function() {
            $('#Password').attr('type', $(this).is(':checked') ? 'text' : 'password');
        });
    });
</script>


</html>