<?php

use dawfony\Ti;
global $URL_PATH;
?>

<?php Ti::extend("view/MainView.phtml"); ?>

<?php Ti::startBlock("content"); ?>
  <!-- Si hay sesion iniciada por login -->
  <?php if (isset($_SESSION["login"])) : ?>
    <div class="container-fluid" style="border:1px solid black">
    <a href="#"><div class="imagen-fondo-sesion"><!-- Redireccionar para meter emails y consiga 10 hechizos -->  
    </div></a>
    <div class="grid-container-sesion container">
            <!-- ********************** Fotos de personas (chicas) imaginarias para hacer al usuario que se registre ******************************************* -->
            <?php  foreach ($sacarLista as $sacarListaSesion) :  ?>
                <div class="container-images-sesion">
                    <img class="imagenes-genero" src="<?= $URL_PATH ?>/assets/fotosMAinImaginario/fotos<?= $sacarListaSesion["genero"] ?>s/<?= $sacarListaSesion["fotos"] ?>" width="100px" height="100px" alt="Busco_Genero">
                    <a href="#" data-toggle="modal" data-target="#modalContactForm">
                        <div class="middle ">
                            <div class="text">
                                <b><?= $sacarListaSesion["login"] ?></b><br><?= $sacarListaSesion["edad"] ?> AÑOS<br> <?= $sacarListaSesion["ubicacion"] ?>
                            </div>
                        </div>
                    </a>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<!-- Aqui el nuevo cuerpo  que será igual asi pero quitando varias cosas y añadiendo otras -->

<?php else : ?>
<div class="container-fluid">
    <div class="imagen-fondo">
        <div class="container-fluid ">
            <div class="inscripcion cajaInscripcion">
                <br>
                <h1>Inscripción gratuita</h1>
                <p class="">en menos de un minuto</p>
                <div class="">
                    <div class="text-center">
                        <a href="" class="btn btn-block mb-4 flickr" data-toggle="modal" data-target="#modalContactForm">
                            ME INSCRIBO</a>
                    </div>
                    <a href=" <?= $login_url ?>" class="btn btn-block mb-4 btn-social btn-facebook" id="fbook">
                        <i class="fa fa-facebook"></i> Conexión vía Facebook </a>

                </div>
            </div>
        </div>
    </div>
    <div class="container fondo-personas">
        <hr>
        <p style="color:black">ELLOS ESTÁN EN LA TIENDA</p>
        <!-- ********************** Fotos de personas (chicos) imaginarias para hacer al usuario que se registre ******************************************* -->
        <div class="grid-container-chicosFondo container">
            <a data-toggle="modal" data-target="#modalContactForm"><img src="<?= $URL_PATH ?>/assets/fotosInterfaces/tatuados.jpg" width="350px" height="350px" alt="tatuado"></a>
            <a data-toggle="modal" data-target="#modalContactForm"><img src="<?= $URL_PATH ?>/assets/fotosInterfaces/romanticos.jpg" width="350px" height="350px" alt="romantico"></a>
            <a data-toggle="modal" data-target="#modalContactForm"><img src="<?= $URL_PATH ?>/assets/fotosInterfaces/gafas.jpg" width="350px" height="350px" alt="gafas"></a>
        </div>
        <hr>
        <p style="color:black">ELLAS ESTÁN EN LA TIENDA</p>
        <div class="grid-container-chicos container ">
            <!-- ********************** Fotos de personas (chicas) imaginarias para hacer al usuario que se registre ******************************************* -->
            <?php foreach ($sacarListaMenu as $sacarMujeresListaMenu) :  ?>
                <div class="container-images">
                    <img class="grid-item imagenes-genero" src="<?= $URL_PATH ?>/assets/fotosMAinImaginario/fotosChicas/<?= $sacarMujeresListaMenu["fotos"] ?>" width="160px" height="160px" alt="chica1">
                    <a href="#" data-toggle="modal" data-target="#modalContactForm">
                        <div class="middle">
                            <div class="text">
                                <b><?= $sacarMujeresListaMenu["login"] ?></b><br><?= $sacarMujeresListaMenu["edad"] ?> AÑOS<br> <?= $sacarMujeresListaMenu["ubicacion"] ?>
                            </div>
                        </div>
                    </a>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>
            <?php endif; ?>
<?php Ti::endBlock(); ?>


<?php Ti::endExtend(); ?>