<?php
use dawfony\Ti;
$session = mt_rand(1,999);
global $URL_PATH;
//echo $login;
//echo $fotoPerfil;
/*esto tienes que ponerlo en postcontroller antes de cargar esta vista y que pase la direccion de la foto del perfil
var_dump($_SESSION["fotoPerfil"]);
        die();*/
        
?>
<!--<link rel="stylesheet" type='text/css' href="<?= $URL_PATH ?>/css/chatcss.css">-->

<?php Ti::extend("view/mainview.phtml"); ?>
<?php Ti::startBlock("content"); ?>


 <!-- boton flotante -->
 <div id="container-floating">
  <div class="nd5 nds" data-toggle="tooltip" data-placement="left" data-original-title="Simone"></div>
  <div class="nd4 nds" data-toggle="tooltip" data-placement="left" data-original-title="contract@gmail.com"><img class="reminder">
    <p class="letter">C</p>
  </div>
  <div class="nd3 nds" data-toggle="tooltip" data-placement="left" data-original-title="Reminder"><p class="letter">B</p></div>
  <div class="nd1 nds" data-toggle="tooltip" data-placement="left" data-original-title="Edoardo@live.it"><img class="reminder">
    <p class="letter">A</p>
  </div>

  <div id="floating-button" data-toggle="tooltip" data-placement="left" data-original-title="Create" onclick="">
    <p class="plus">+</p>
    <img class="edit" src="https://ssl.gstatic.com/bt/C3341AA7A1A076756462EE2E5CD71C11/1x/bt_compose2_1x.png">
  </div>
</div>

<div id="superponiendo">
    <div id="contactform" class="container">
        <div id="contact-button">
            <div class="rotated-text"><?php echo $xateaCon ?></div>
        </div>
        <div class="container p-2">
            <div class="container text-white text-center py-auto" id="cabeceradelxat">
                <span></span>
                <h4><img class="inlineIcon mb-2 mr-2" src="assets/fotosInterfaces/logo.png">&nbsp;<u><?php echo $login ?></u></h4>
            </div>
        </div>


        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-12 col-lg-12 pb-0" id="ventanaXatRosa">
                <div id="formuXat" class="mCustomScrollbar" data-mcs-theme="minimal-dark">
                    <div class="card rounded-0" id="fondoBurbujastext">
                        <div class="bubbleWrapper">
                            <div class="inlineContainer ml-1">
                                <img class="inlineIcon" src="<?php echo $fotoPerfil;?>">
                                <div class="otherBubble other">
                                    <span class="other text-primary"><?php echo date('H:i');?></span> No reveles contraseñas ni otros datos importantes!
                                </div>
                            </div>
                        </div>

                        <div id="chat_output">

                        </div>
                        <div class="card-body p-0">                   
                        </div>
                    </div>
                </div>
            </div>

            <div class="container mb-2">
                <input type="text" class="form-control mt-2 container" id="chat_input" placeholder="Escribir mensaje">                
            </div>
        </div>
    </div>
</div>

<script>
        var session = "<?php echo $session; ?>"; // Pasamos la session de php al ratchet.js.
        var fotoPerfil = "<?php echo $fotoPerfil;?>";
        var fotoPerfilB = "<?php echo $fotoPerfilB;?>";
</script>
<script src="<?= $URL_PATH ?>/js/ratchetClient.js"></script>
<script src="<?= $URL_PATH ?>/js/chatWindowx.js"></script>



<!-- Si hay sesion iniciada por login -->
<?php if (isset($_SESSION["login"])) : ?>
<div class="container">
    <!-- ruta para conseguir mas hechizos al clikeo manda a otra pagina para ingresar email nuevo. -->
    <a href="<?= $URL_PATH ?>/hechizos/<?= $_SESSION["login"] ?>">
        <div class="imagen-fondo-sesion">
            <!-- Redireccionar para meter emails y consiga 10 hechizos -->
        </div>
    </a>

    <div class="container fondo-personas">
        <div class="grid-container-sesion container-fluid">
            <!-- ********************** Fotos de personas (chicas) imaginarias para hacer al usuario que se registre ******************************************* -->
            <?php foreach ($sacarLista as $sacarListaSesion) :  ?>
            <div class="container-images-sesion container-fluid">
                <img class="imagenes-genero-sesion" src="<?= $URL_PATH ?>/assets/fotosUsuarios/fotos<?= $sacarListaSesion->genero?>s/<?= $sacarListaSesion->foto ?>" alt="no_foto">
                <!-- crear ruta para que nos lleve al perfil del usuario clickeado con su login-->
                <a href="<?= $URL_PATH ?>/perfilUsuario/<?= $sacarListaSesion->login ?>">
                    <div class="middle">
                        <div class="text style-font">
                            <b><?= $sacarListaSesion->login ?></b><br><?= $sacarListaSesion->edad ?> años<br> <?= $sacarListaSesion->ubicacion ?>
                        </div>
                    </div>
                </a>
            </div>
            <?php endforeach; ?>
        </div>
    </div>
    <nav aria-label="...">
        <ul class="pagination">
            <li class="page-item <?= ($pagina  <= 1 ? "disabled" : "") ?>">
                <a class="page-link" href="<?= $ruta . ($pagina - 1) ?>" tabindex="-1" aria-disabled="true">Anterior</a>
            </li>
            <?php
                    for ($i = 1; $i <= $numpaginas; $i++):?>

            <li class="page-item ">
                <a class="page-link" href="<?= $ruta ?><?= $i ?>"><?= $i ?></a>
            </li>

            <?php
                        endfor;
                    ?>
            <li class="page-item <?= ($pagina + 1 > $numpaginas ? "disabled" : "") ?>">
                <a class="page-link" href="<?= $ruta . ($pagina + 1) ?>" aria-disabled="true">Siguiente</a>
            </li>
        </ul>
    </nav>
</div>
<!-- Aqui el nuevo cuerpo  que será igual asi pero quitando varias cosas y añadiendo otras -->
<?php else : ?>
<div class="container-fluid container">
    <div class="container fondo-personas">
        <br>
        <hr>
        <p class="p-listado">ELLOS ESTÁN EN LA TIENDA</p>

        <!-- ********************** Fotos de personas (chicos) imaginarias para hacer al usuario que se registre ******************************************* -->
        <div class="grid-container-chicosFondo container">
            <a data-toggle="modal" data-target="#modalContactForm"><img src="<?= $URL_PATH ?>/assets/fotosInterfaces/tatuados.jpg" width="350px" height="350px" alt="tatuado"></a>
            <a data-toggle="modal" data-target="#modalContactForm"><img src="<?= $URL_PATH ?>/assets/fotosInterfaces/romanticos.jpg" width="350px" height="350px" alt="romantico"></a>
            <a data-toggle="modal" data-target="#modalContactForm"><img src="<?= $URL_PATH ?>/assets/fotosInterfaces/gafas.jpg" width="350px" height="350px" alt="gafas"></a>
        </div>
        <hr>
        <p class="p-listado">ELLAS TAMBIÉN ESTÁN EN LA TIENDA</p>
        <div class="grid-container-chicos container ">
            <!-- ********************** Fotos de personas (chicas) imaginarias para hacer al usuario que se registre ******************************************* -->
            <?php foreach ($sacarListaMenu as $sacarMujeresListaMenu) :  ?>
            <div class="container-images">
                <img class="grid-item imagenes-genero" src="<?= $URL_PATH ?>/assets/fotosUsuarios/fotosChicas/<?= $sacarMujeresListaMenu["fotos"] ?>" width="160px" height="160px" alt="chica1">
                <a href="#" data-toggle="modal" data-target="#modalContactForm">
                    <div class="middle">
                        <div class="text style-font">
                            <b><?= $sacarMujeresListaMenu["login"] ?></b><br><?= $sacarMujeresListaMenu["edad"] ?> años<br> <?= $sacarMujeresListaMenu["ubicacion"] ?>
                        </div>
                    </div>
                </a>
            </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>
<?php endif; ?>
<?php Ti::endBlock(); ?>


<?php Ti::endExtend(); ?>
