<?php
// necesitamos la trayectoria de la URL para formar las rutas:
global $URL_PATH;
global $login_url;
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="robots" content="noindex,nofollow">

    <title>
        <?php \dawfony\Ti::startBlock("title"); ?>
        SocialLove
        <?php \dawfony\Ti::endBlock(); ?>
    </title>

    <?php /* jquery cdn */ ?>
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <?php /* Bootstrap. Las rutas deben ser absolutas, porque estamos haciendo rewrite */ ?>
    <link rel="stylesheet" href="<?= $URL_PATH ?>/vendor/twbs/bootstrap/dist/css/bootstrap.min.css">
    <script src="<?= $URL_PATH ?>/vendor/twbs/bootstrap/dist/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="<?= $URL_PATH ?>/node_modules/bootstrap-social/bootstrap-social.css">
    <?php /* Font awesome CDN */ ?>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/font-awesome.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/solid.min.css">
    <link rel="stylesheet" href="<?= $URL_PATH ?>/node_modules/font-awesome/css/font-awesome.min.css">
    <?php /* Animate.css CDN */ ?>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
    <?php /*Para añadir lineas al head desde las plantillas derivadas*/ ?>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <link rel="stylesheet" type='text/css' href="<?= $URL_PATH ?>/css/cssMainView.css">
    <!-- DEJO ESTO PORQUE ME DA PROBLEMAS CON EL CSS AL METER UNA VARIABLE PHP ESTÁ INYECTADO DE MOMENTO A PINCHO EN LA MISMA LINEA -->
    <!-- <link rel='stylesheet' type='text/css' href='<?= $URL_PATH ?>/css/cssMain.php' /> -->
    <link rel="shortcut icon" href="<?= $URL_PATH ?>/assets/fotosInterfaces/logo-fb.png" />
    <!-- FONT FAMILY -->
    <link href="https://fonts.googleapis.com/css?family=Righteous&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Special+Elite&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Prata&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">

    <?php /* Script de carpeta JS*/ ?>
    <script src="<?= $URL_PATH ?>/js/mensajesContadores.js"></script>
    <script src="<?= $URL_PATH ?>/js/contador.js"></script>
    <script src="<?= $URL_PATH ?>/js/validarTarjerta.js"></script>
    <script src="<?= $URL_PATH ?>/js/clickVip.js"></script>
    <script src="<?=$URL_PATH ?>/js/validarformulariozonavip.js"></script>
    <script src="<?=$URL_PATH ?>/Pawel/jquery.creditCardValidator.js"></script>
    

    <script>
        var URL_PATH = "<?= $URL_PATH ?>"; // Pasamos el URL_PATH de php a Javascript.
        var error = false; //esto es para el formulario login y  comprobamos si el email que ha introducido está bien sino que lo escriba de nuevo.
    </script>

    <?php \dawfony\Ti::startBlock("head"); ?>
    <?php \dawfony\Ti::endBlock(); ?>
</head>


<body class="imagen-fondo-body" style="background-image: url('<?= $URL_PATH ?>/assets/fotosInterfaces/fondoBody.png');
    background-repeat: repeat;
    background-color: #fbf6f9;">

    <div class="jumbotron">
        <header>
            <div class="img-container img-logo-vip">
                <img class="img-fluid img-logo " src="<?= $URL_PATH ?>/assets/fotosInterfaces/logo.png" data-srcpng="" alt="socialLoveLogo">
                <h1 class="img-logo logo-h1 ">SOCIAL LOVE</h1>
            </div>
        </header>
    </div>
    <div style="background-color:white;" class="container" id="">
        <div class=" grid-container-zonaVip">
            <div class="card-deck mb-3 text-center">
                <!-- solo son 4 cards -->
                <div class="card mbd-4 shadow-sm sinclick-body clickbody" id="1" onclick="clickVip(1)">
                    <div class="card-header sinclick-header clickheader" id="11">
                        <h4 class="my-0 font-weight-bold fontfamilyvip ">VIP 6 MESES</h4>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title"><span class="vipFont">8,80</span><span class="vipFont" style="font-size:24px;">&euro;</span><span style="font-size:12px; color:black;">/MES</span></h1>
                        <div class="vipfontsquad">
                            <span class="vipFont"> 25 HECHIZOS </span>/MES
                        </div>
                        <ul class="list-unstyled mt-3 mb-4">
                            <li class="li-vip">20,78&euro; DE AHORRO</li>
                        </ul>
                    </div>
                    <h6 style="font-size:10px;">En un pago de 52,80 &euro;</h6>
                </div>

                <div class="card mbd-4 shadow-sm sinclick-body clickbody" id="2" onclick="clickVip(2)">
                    <div class="card-header  sinclick-header clickheader" id="21">
                        <h4 class="my-0 font-weight-bold fontfamilyvip">VIP 3 MESES</h4>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title"><span class="vipFont">10,80</span><span class="vipFont" style="font-size:24px;">&euro;</span><span style="font-size:12px; color:black;">/MES</span></h1>
                        <div class="vipfontsquad">
                            <span class="vipFont"> 15 HECHIZOS</span>/MES
                        </div>
                        <ul class="list-unstyled mt-3 mb-4">
                            <li class="li-vip">18,78&euro; DE AHORRO</li>
                        </ul>
                    </div>
                    <h6>En un pago de 32,40 &euro;</h6>
                </div>

                <div class="card mbd-4 shadow-sm sinclick-body clickbody" id="3" onclick="clickVip(3)">
                    <div class="card-header sinclick-header clickheader" id="31">
                        <h4 class="my-0 font-weight-bold fontfamilyvip">VIP 1 MES</h4>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title"><span class="vipFont">16,80</span><span class="vipFont" style="font-size:24px;">&euro;</span><span style="font-size:12px; color:black;">/Mes</span></h1>
                        <div class="vipfontsquad">
                            <span class="vipFont">5 HECHIZOS /MES</span>
                        </div>
                        <ul class="list-unstyled mt-3 mb-4">
                            <li class="li-vip">12,78&euro; DE AHORRO</li>
                        </ul>
                    </div>
                    <h6>En un pago de 16,80 &euro;</h6>
                </div>
 
                <div class="card mbd-4 shadow-sm sinclick-body clickbody" id="4" onclick="clickVip(4)">
                    <div class="card-header sinclick-header clickheader" id="41">
                        <h4 class="my-0 font-weight-bold fontfamilyvip">DISCOVERY</h4>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title"><span class="vipFont">6,90</span><span class="vipFont" style="font-size:24px;">&euro;</span><span style="font-size:12px; color:black;">/SEM</span></h1>
                        <div class="vipfontsquad">
                            <span class="vipFont">2 HECHIZOS /SEM</span>
                        </div>
                        <ul class="list-unstyled mt-3 mb-4">
                            <li class="li-vip">0,98&euro;/AL DIA</li>
                        </ul>
                    </div>
                    <h6>En un pago de 6,90 &euro;</h6>
                </div>
            </div>
        </div>
        <hr>
        <!-- AQui está el resumen y tarjeta -->
        <div class="container-fluid div-resumen" id="">
        <form action="<?=$URL_PATH?>/pasarela" method="post" id="paymentForm" class="container-fluid resumenletra div-resumen" onsubmit="return validarformulariozonavip()">
            <div class="grid-container-zonaVip-resumen">
                <div class="container-fluid resumenletra">
                    RESUMEN
                    <hr>
                    <span class="resumen-elegido">
                        <i id="idpaquete" name="idpaquete" style="display:none"></i>
                        <b>Aqui: <span id="titulo"></span></b> <span class="resumenvip" id="preciodia">/día</span>
                        <br>
                        En un pago de <b><span id="precio"> &euro;</span>
                            <br>
                            <span class="acepted-cgu">Al validar el pedido, estoy aceptando las <a class="cgu" href="#" data-toggle="modal" data-target="#aceptedCGU">CGU</a></span>
                    </span>
                </div>

                <div class="container-fluid resumenletra">
                    <!-- la tarjeta tiene que ser de forma reducida. el titulo arriba y los datos abajo. -->
                    <script>
                        $(document).ready(function() {
                            //card validation on input fields
                            $('#paymentForm input[type=text]').on('keyup', function() {
                                validarTarjeta();
                            });
                        });
                    </script>
                    TARJETA DE CREDITO
                    <hr><!-- TENGO PROBLEMA CON VALIDAR TARJETA HAY QUE MIRARLO -->
                    <i id="tarjetacomprobada" style="display:none"></i>
                    <div class="form-group grid-container-zonaVip-resumen  resumen-elegido">
                        <label class="">Número de la tarjeta:</label>
                        <input type="text" class="form-control select-vip" id="card_number" name="tarjeta"  placeholder="1234 5678 9012 3456" maxlenght="16" autocomplete="off">
                        <span class="errorTarjeta"><b id="errorTarjeta"></b></span>
                        <span class="visaCorrecto"><b id="visaCorrecto"></b></span>
                        <label for="inputState">Validez</label>
                        <input class="select-vip" type="text" name="expiry_date" id="expiry_date" maxlength="5" placeholder="MM/YY" >
                        <label for="cvv">CVV</label>
                        <input type="text" class="select-vip" id="cvv" name="cvv" placeholder="CVV" autocomplete="off" min="3" max="3" maxlength="3">
                    </div>
                </div>
            </div>
        </div>

        <button type="submit" class="btn btn-primary btn-block boton-confirm-tarjet" id="procesarCompra"><i class="fas fa-lock"></i>&nbsp;Confirmar el pago</button>
        </form>
        <div class="container-fluid viplittleletter">
            VIP 6 meses con 25 Hechizos mensuales, facturados en 1 pago inmediatio de 52,80 € TTC, con una duración de 6 meses. Al terminar tu abono este será automáticamente reconducido a un periodo idéntico al precedente y con las mismas condiciones.; VIP 3 meses con 15 Hechizos mensuales, facturados en 1 pago inmediatio de 32,40 € TTC, con una duración de 3 meses.; VIP 1 mes con 5 Hechizos mensuales, facturados en 1 pago inmediatio de 16,80 € TTC, con una duración de 1 mes. ; Pass Discovery con 2 Hechizos, facturados en 1 pago inmediatio de 6,90 € TTC, con una duración de 7 días. Para los abonos mensuales, el precio diario indicado ha sido calculado en base a un mes de 30 días. Puedes ejercitar tu derecho de retractación durante los 14 días posteriores a tu compra. Para más información sobre las condiciones de reembolso y de los abonos por favor, consulta las Condiciones Generales de Uso.
        </div>
    </div>

    <!-- ********************** Modal ******************************************* -->

    <div class="modal fade" id="aceptedCGU" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-scrollable" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalScrollableTitle">CONDICIONES</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body font-modal-cgu">
                    <?php
                    $condiciones = file_get_contents('conditions/condiciones.txt');
                    $condiciones = nl2br($condiciones);
                    echo $condiciones;
                    ?>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <?php \dawfony\Ti::extend("view/footerView.phtml"); ?>
    <?php \dawfony\Ti::endExtend(); ?>
</body>

</html>